name: Build and deploy static website
on:
  - workflow_dispatch
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 17.2.0
        uses: actions/setup-node@v2
        with:
          node-version: '17.2.0'
      - name: Build web resources
        run: ./tools/build-web.sh
        env:
          DIAFORM_API_HOST: ${{secrets.api_host}}
      - name: Deploy to Azure Storage and purge Cloudflare cache
        run: ./tools/deploy-static.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{secrets.azure_storage_account}}
          AZURE_STORAGE_KEY: ${{secrets.azure_storage_key}}
          CLOUDFLARE_ZONE: ${{secrets.cloudflare_zone}}
          CLOUDFLARE_TOKEN: ${{secrets.cloudflare_token}}
