name: Deploy application
on:
  push:
    branches:
      - master
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Build and push Docker image
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: c2d7fa/thinktool
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_password}}
          dockerfile: tools/Dockerfile
          tags: latest,prod
      - name: Run deployment script on server
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{secrets.host}}
          username: root
          key: ${{secrets.key}}
          script: ./deploy-diaform.sh
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Wine (for building desktop client)
        # https://github.com/actions/virtual-environments/issues/743#issuecomment-616349857
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt install --install-recommends winehq-stable
      - name: Build static resources
        run: ./tools/build-client.sh && ./tools/build-desktop.sh && ./tools/build-static.sh
        env:
          DIAFORM_API_HOST: ${{secrets.api_host}}
      - name: Deploy to Azure Storage and purge Cloudflare cache
        run: ./tools/deploy-static.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{secrets.azure_storage_account}}
          AZURE_STORAGE_KEY: ${{secrets.azure_storage_key}}
          CLOUDFLARE_ZONE: ${{secrets.cloudflare_zone}}
          CLOUDFLARE_TOKEN: ${{secrets.cloudflare_token}}
