name: Build and deploy desktop clients
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
  desktop-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 17.2.0
        uses: actions/setup-node@v2
        with:
          node-version: '17.2.0'
      - name: Build desktop client for Linux
        run: |
          cd src/desktop
          yarn install --frozen-lockfile
          yarn run bundle-linux
        env:
          DIAFORM_API_HOST: ${{secrets.api_host}}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: 'src/desktop/dist/Thinktool*.AppImage'
  desktop-windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node 17.2.0
        uses: actions/setup-node@v2
        with:
          node-version: '17.2.0'
      - name: Build desktop client for Windows
        run: |
          cd src/desktop
          yarn install --frozen-lockfile
          yarn run bundle-windows
        shell: bash
        env:
          DIAFORM_API_HOST: ${{secrets.api_host}}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: 'src/desktop/dist/Thinktool*.exe'

