name: Build server Docker image
on:
  - workflow_dispatch
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: c2d7fa/thinktool:latest
          file: tools/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
