name: Run automated tests
on:
  - push
jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd src/shared && sudo npm link && cd ../..
          cd src/client && npm link @thinktool/shared && npm ci
      - name: Run test suite
        run: cd src/client && npm run test
