name: Run automated tests
on:
  - push
jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 15.14.0
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
      - name: Install dependencies
        run: |
          cd src
          yarn install --frozen-lockfile
          cd shared && yarn run build && cd ..
          cd search && yarn run build && cd ..
      - name: Run test suite
        run: cd src/client && yarn run test
